### ISSUE TITLE
Cached times aren't working, even in previous releases

### ISSUE THREAD

**Issue by KiARC** [KiARC/Sobriety#12]
I am 100% sure they worked before but now on every release on multiple devices the cached times don't reset correctly

Expected: Reset time, close and open app, time is relatively small because of the recent reset
Actual: Reset time, close and open app, time is back where it was

I am genuinely baffled.

**Comment by KiARC** [comment]
Honestly what even *could* cause this? A spontaneous bug affecting all versions that was definitely not there before just isn't possible.

**Comment by JakeGonder** [comment]
The problem seems to be in line 129 in Main.kt:

```
date = Instant.now()
```

This creates a new Instant with the correct current date. `date` then points to this new Instant, but the Instant in the HashMap is never updated. This `date` reference is also used to update the displayed text, which is why everything appears to be working as expected.

In the previous versions this could be fixed, by updating `addictions[name]` directly, instead of the local variable `date`. In the current version, where addiction is a HashMap of a String and a Pair, the equivalent would be updating it via
 ```
addictions[key].first = Instant.now()
```
 however Pair is immutable, thats why my current workaround is constructing a new Pair using the updated date and the old Buffer like so:

```
 addictions[key] = Pair(Instant.now(), addictions[key]!!.second)
```

Im sure there is a cleaner way to do it but this seems to work

**Comment by KiARC** [comment]
Ahhhh that makes sense. I might write a really simple Pair implementation that is mutable to make the fix more readable. Thanks for explaining that haha

**Comment by JakeGonder** [comment]
I was confused about this as well at first😄 This [stackoverflow answer](https://stackoverflow.com/a/40523/13139418) basically explains it very nice in detail. Just like Java, Kotlin is pass-by-value, e.g. it passes a copy of of a reference to a method, so reassigning this copy to a new object does not change the original.

**Comment by JakeGonder** [comment]
> I might write a really simple Pair implementation that is mutable

Maybe its a better idea, to just create a serializable class "Addiction", with fields name, date, buffer etc. and save that as an ArrayList<Addiction>, then `createNewCard` could take an Addiction object as input, and simply modify the fields of this object.

This would also make it easier to add new fields later on, (e.g. total money / time saved?), because you wouldnt need to continue stacking Pairs into Pairs

**Comment by KiARC** [comment]
Ahaha I feel so stupid now. I wrote it the way I did at first because I thought Kotlin was PBR but thanks for explaining that.

**Comment by KiARC** [comment]
And yeah that's a good idea

**Comment by KiARC** [comment]
Closing now because a solution has been found, thanks so much ^^
