### ISSUE TITLE
It's crashing again :/

### ISSUE THREAD

**Issue by KiARC** [KiARC/Sobriety#21]
I'll debug it later when I have time

**Comment by KiARC** [comment]
I can confirm that the issue is exclusively with v4.0.1

**Comment by KiARC** [comment]
Strangely enough it only happens with the release build.

**Comment by KiARC** [comment]
And only on my physical device, like I said :\

**Comment by JakeGonder** [comment]
If you connect your phone via USB and enable USB debugging you can view the Logcat of your phone in Android Studio, it should show you the crash log.

**Comment by JakeGonder** [comment]
> Strangely enough it only happens with the release build.

Then this is probably a gradle issue, you could also try to go into "Edit configuration" and under Installation options, select "APK from app bundle" under deploy
![grafik](https://user-images.githubusercontent.com/51212295/169747989-131d9b67-14e8-4440-8aa8-ed1223e5ca89.png)
If the crash is caused by the app bundle, this could cause the crash to also appear in the emulator, making it easier to debug than on your physical device, but if this doesn't work, using Logcat as described above to view your phones Crash log should work too.

**Comment by KiARC** [comment]
I debugged on my phone a couple weeks ago, forgot to update but the crashes seem to happen when an empty cache is saved as the first cache. i.e. if you open the app, trigger a cache save and close it, then it won't open again, but if you open the app, create an addiction card, trigger a save, delete it, then trigger another save it works fine. I'm not sure what's even wrong, it was throwing IO errors.

**Comment by KiARC** [comment]
I may be absent for.a while due to mental health issues, but I'm not abandoning the project, don't worry.

**Comment by JakeGonder** [comment]
I will take a look at it next week and try to reproduce / debug it. Hope you feel better soon!

**Comment by JakeGonder** [comment]
v4.0.1 is the one currently live in IzzyOnDroid right? I tried what you said, clean install on my phone, trigger empty save by opening and closing the app, for me everything works fine, no crashes,

**Comment by KiARC** [comment]
I'm back! And yeah the crashing might be an issue on my device because I recently got a new phone and it isn't having any issues there. Expect a new release soon!
