### ISSUE TITLE
option for years months days hours minutes

### ISSUE THREAD

**Issue by nutpantz** [KiARC/Sobriety#24]
While it's nice to have days hours, etc, not so much after you have over 1000 days.
It's much more readable if there was an option for years, months, days, hours seconds.

Personally i don't even need exact months since one is 28 days and others are 30 or 31, but it would be nice for the crazy exact people.

**Comment by KiARC** [comment]
That's a good idea. Maybe it should start displaying `months, days, hours, minutes` at 31 days, and then `years, months, days, hours` at 12 months. Shouldn't be *too* difficult to write, and assuming that that proves true it might be in a coming update \^\^

**Comment by nutpantz** [comment]
That sounds fantastic

**Comment by Taxit0m** [comment]
This feature was added but it displays incorrect information because the author didnt account for all months not having 31 days, you might as well throw the output in the garbage, scrap the app, discontinue development, and uninstall it because the author stated this was expected, wouldn't be labeled as a bug, and had 0 intentions of fixing it.

**Comment by nutpantz** [comment]
I'm not that anal about time and date.
I'll keep using it
