### ISSUE TITLE
Milestones and Savings disappear

### ISSUE THREAD

**Issue by inuitviking** [KiARC/Sobriety#57]
The milestones and savings disappear when closing the milestones and savings view.

Here is a Youtube Short of the bug https://youtu.be/0iBE2V1FUvA

Don't ask me why a short; Youtube decided it was a short.

I am running the latest version available on F-Droid (just updated and tested before posting the issue).

- OnePlus 6 (A6003)
- OxygenOS 11.1.2.2 (Android version 11)
- Sobriety v7.0.0
- F-Droid 1.15.4

**Comment by KiARC** [comment]
I've noticed this myself recently and am trying to figure out what causes it. Hopefully will be fixed soon.

**Comment by cubandle** [comment]
I used git bisect to isolate the behavior to this commit: 60d3aec47d009898a4a1d4249f7623854162ca35

I noticed that milestones created before this commit will display correctly even after this commit, so I think the bug has to do with saving the milestone.

I am not familiar with Android development. Is it possible that a copy of the addiction is obtained [here](https://github.com/KiARC/Sobriety/blob/60d3aec47d009898a4a1d4249f7623854162ca35/app/src/main/java/com/katiearose/sobriety/activities/Milestones.kt#L32) rather than the original? I found a [post](https://stackoverflow.com/questions/51198626/android-intent-putextra-changes-objects) that suggests that. If that's true, then modifying the addiction object only modifies the copy obtained from putExtra rather than the saved original.
